{
 "title": "Model-Dashboard",
 "time": { "from": "2024-10-13T13:56:40.784Z", "to": "2024-10-13T18:28:10.706Z" },
 "panels": [
  { "title": "Model Regression Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "R2 Score",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, model_r2_score{instance!~\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "R2 Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "model_r2_score{service=\"retrain-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MSE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, model_mse{instance!~\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RMSE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, model_rmse{instance!~\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MSE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "model_mse{service=\"retrain-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RMSE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "model_rmse{service=\"retrain-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Model Classification Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "F1 Score",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, model_f1_score{instance!~\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "F1-Score",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "model_f1_score{service=\"retrain-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Precision",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "model_precision{service=\"retrain-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recall",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "targets": [
    { "expr": "model_recall", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Accuracy",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, model_accuracy{instance!~\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "model_accuracy{service=\"retrain-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    { "expr": "node_memory_Active_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}