apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app-deployment
  labels:
    app: ml-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ml-app
  template:
    metadata:
      labels:
        app: ml-app
    spec:
      containers:
      - image: 206479108282.dkr.ecr.us-east-1.amazonaws.com/model_bucket_ecr:691421c9-9674-4d9b-bcd4-987f7c784eb3
        name: ml-app
      imagePullSecrets:
      - name: us-east-1-ecr-registry
