apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ml-app-lb-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.86.15-192.168.86.25
  autoAssign: true

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ml-app-lb-pool-ad
  namespace: metallb-system
