apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-volume
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt"
    type: Directory