apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: retrain-service-monitor
  labels:
    release: prometheus 
    app: prometheus
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: retrain-service
  endpoints:
    - interval: 5s
      port: web
      path: /metrics