name: "Continuous Deployment"

on:
    workflow_run:
      workflows: 
        - Set up cloud resources
      types:
        - completed

env:
  GOOGLE_CREDENTIALS:    ${{ secrets.GOOGLE_CREDENTIALS }}
  AWS_REGION:            ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY:        ${{ secrets.ECR_REPOSITORY }}
  ACCOUNT_ID:            ${{ secrets.ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  MODEL_REQS_BUCKET:     ${{ secrets.MODEL_REQS_BUCKET }}
  MODEL_FILES_BUCKET:    ${{ secrets.MODEL_FILES_BUCKET }}
  PROJECT_ID:            ${{ secrets.GCP_PROJECT_ID }}
  BACKEND_SERVICE:       ${{ secrets.GCP_CLOUDRUN_SERVICE_BACKEND }}
  FRONTEND_SERVICE:      ${{ secrets.GCP_CLOUDRUN_SERVICE_FRONTEND }}
  DB_URI:                ${{ secrets.DB_URI }}
  GH_TOKEN:              ${{ secrets.GH_TOKEN }}
  JWT_SECRET:            ${{ secrets.JWT_SECRET }}
  VITE_BACKEND_URI:      ${{ secrets.VITE_BACKEND_URI}}
  FRONTEND_URI:          ${{ secrets.FRONTEND_URI}}


jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ env.GOOGLE_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.GOOGLE_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.BACKEND_SERVICE }}:latest
          build-args: |
            DB_URI=${{env.DB_URI}}
            AWS_ACCESS_KEY=${{env.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY=${{env.AWS_SECRET_ACCESS_KEY}}
            GH_TOKEN=${{env.GH_TOKEN}}
            JWT_SECRET=${{env.JWT_SECRET}}
            VITE_BACKEND_URI=${{env.VITE_BACKEND_URI}}
            FRONTEND_URI=${{env.FRONTEND_URI}}
            COMMAND=start

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.BACKEND_SERVICE }}:latest
          service: ${{ env.BACKEND_SERVICE }}
          region: us-central1
          platform: managed
          allow-unauthenticated: true
          env_vars: |
              FOO=bar
              ZIP=zap
  
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ env.GOOGLE_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.GOOGLE_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.FRONTEND_SERVICE }}:latest
          build-args: |
            DB_URI=${{env.DB_URI}}
            AWS_ACCESS_KEY=${{env.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY=${{env.AWS_SECRET_ACCESS_KEY}}
            GH_TOKEN=${{env.GH_TOKEN}}
            JWT_SECRET=${{env.JWT_SECRET}}
            VITE_BACKEND_URI=${{env.VITE_BACKEND_URI}}
            FRONTEND_URI=${{env.FRONTEND_URI}}
            COMMAND=frontend

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.FRONTEND_SERVICE }}:latest
          service: ${{ env.FRONTEND_SERVICE }}
          region: us-central1
          platform: managed
          allow-unauthenticated: true
          env_vars: |
              FOO=bar
              ZIP=zap
        