name: "Deploy model Tier 2"


on:
    push:
      branches:
        - main

env:
  AWS_REGION:            ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY:        ${{ secrets.ECR_REPOSITORY }}
  ACCOUNT_ID:            ${{ secrets.ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_BUCKET:             ${{ secrets.MB_BUCKET }}
  MODEL_FILES_BUCKET:    ${{ secrets.MODEL_FILES_BUCKET }}
  BACKEND_URL:           ${{ secrets.VITE_BACKEND_URI }}
  HETZNER_TOKEN:         ${{ secrets.HETZNER_TOKEN }}
  HETZNER_SSH_KEY:       ${{ secrets.HETZNER_SSH_KEY }}


jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: webfactory/ssh-agent@v0.4.1
              with:
                ssh-private-key: ${{ env.HETZNER_SSH_KEY }}
            - run: |
                ssh -o StrictHostKeyChecking=no root@${{ env.SERVER_IPV4 }} << "EOF"  > temp_output.txt
                    echo "some thing"
                EOF

                G_URL=$(<temp_output.txt)
                echo "::add-mask::$G_URL"
                echo "G_URL=$G_URL" >> $GITHUB_ENV

                rm temp_output.txt
                                